# Generated by Django 5.0.6 on 2024-05-29 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
                ('image_url', models.CharField(max_length=2083)),
                ('category', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('LIKE', 'LIKE'), ('VIEW', 'VIEW'), ('TIME_SPENT', 'TIME_SPENT')], default='VIEW', max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('timespent', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
