# Generated by Django 5.0.6 on 2024-05-29 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_activity',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user_activity',
            name='name',
        ),
    ]
