# Generated by Django 5.0.6 on 2024-05-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
