# Generated by Django 5.0.6 on 2024-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bag_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='size',
            field=models.CharField(max_length=100),
        ),
    ]
