# Generated by Django 5.0.6 on 2024-05-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bag_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rating']},
        ),
        migrations.AlterField(
            model_name='user_activity',
            name='action',
            field=models.CharField(choices=[('LIKE', 'LIKE'), ('VIEW', 'VIEW'), ('TIME_SPENT', 'TIME_SPENT'), ('ADD_TO_BAG', 'ADD_TO_BAG')], default='VIEW', max_length=255),
        ),
    ]
